<?php

namespace CBSE;

use CBSE\Dto\CourseInfoDate;
use DateTime;

class DocumentationPdf extends CBSE_PDF
{
    private CourseInfoDate $course;

    public function __construct(CourseInfoDate $courseInfoDate)
    {
        parent::__construct(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
        $this->course = $courseInfoDate;
    }

    public function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
        $this->unlink();
    }

    /**
     * Delete the generated file
     */
    public function unlink(): bool
    {
        if (file_exists($this->getPdfFile()))
        {
            return unlink($this->getPdfFile());
        }
        return false;
    }

    public function getPdfFile(): string
    {
        return plugin_dir_path(__FILE__) . $this->course->getCourseId() . '_' . $this->course->getCourseDate()
                ->format('Y-m-d') . '.pdf';
    }

    public function generatePdf(): string
    {
        $this->setMetaInformation();

        // Add a page
        // This method has several options, check the source code documentation for more information.
        $this->AddPage();

        $this->AddHeader();

        // Close and output PDF document
        // This method has several options, check the source code documentation for more information.
        return $this->Output($this->getPdfFile(), 'F');
    }

    private function setMetaInformation()
    {
        $courseInfo_categories = !empty($this->course->getEventCategories()) ? implode(", ", $this->course->getEventCategories()->event_categories) : '';
        $date_string = $this->course->getCourseDateString();
        $time_start_string = $this->course->getCourseStartTimeString();
        $time_end_string = $this->course->getCourseEndTimeString();
        $courseInfo_DateTime = $this->course->getCourseDateTimeString();

        // set document information
        $this->SetCreator(PDF_CREATOR);
        $this->SetAuthor('Code.Sport');
        $this->SetTitle("$date_string " . get_option('cbse_options')['header_title']);
        $this->SetSubject("{$courseInfo_categories} | {$this->course->getEvent()->post_title} | {$courseInfo_DateTime}");

        // set default header data
        $this->setPrintHeader(false);
        $this->setFooterData(array(0, 0, 0), array(0, 0, 0));
        $this->setFooterText("{$this->course->getEvent()->post_title} | {$courseInfo_DateTime}");

        // set header and footer fonts
        $this->setHeaderFont(array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
        $this->setFooterFont(array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

        // set default monospaced font
        $this->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

        // set margins
        $this->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_LEFT);
        $this->SetHeaderMargin(0);
        $this->SetFooterMargin(PDF_MARGIN_FOOTER);

        // set auto page breaks
        $this->SetAutoPageBreak(true, PDF_MARGIN_BOTTOM);

        // set image scale factor
        $this->setImageScale(PDF_IMAGE_SCALE_RATIO);

        // set default font subsetting mode
        $this->setFontSubsetting(true);

        // Set font
        // dejavusans is a UTF-8 Unicode font, if you only need to
        // print standard ASCII chars, you can use core fonts like
        // helvetica or times to reduce file size.
        $this->SetFont('dejavusans', '', 10, '', true);
    }

    private function AddHeader()
    {
        $image_id = get_option('cbse_pdf_header_options')['header_image_attachment_id'];
        $image = wp_get_attachment_image($image_id, 700, "", array("class" => "img-responsive"));
        $title = get_option('cbse_pdf_header_options')['title'];

        $html = <<<EOD
            <style>    
                h1 {
                    text-align: center;
                    font-size: 28pt;
                }
            </style>
        EOD;
        if (!empty($image))
        {
            $html .= $image;
        }
        if (!empty($title))
        {
            $html .= "<h1>" . $title . "</h1>";
        }
        $this->writeHTML($html, true, false, true, false, '');
    }
}
